# Site-wide settings
# ------------------

title: CSA Portfolio
description: "Class of 20268"
owner_name: Zhengji Li
github_username: xinjiav2
github_repo: "CSA"
baseurl: "/CSA"
future: true

author:
  name: Zhengji Li
  email: li.xuzhu10@gmail.com
#
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
# description: >
#   Write an awesome description for your new site here. You can edit this line
#   in _config.yml. It will appear in your document head meta (for Google search
#   results) and in your feed.xml site description.


# Build settings
# --------------
#
# Build settings
# --------------

theme: minima
remote_theme: jekyll/minima@d4d779a

plugins:
  - jekyll-feed
  - jekyll-seo-tag
#
# Uncomment the following setting if you wish to disable deprecation warnings
#   from newer versions of sass converter. Adapt as required.
# sass:
#   quiet_deps: true
#   silence_deprecations: [import]


# Minima-specific settings
minima:
  skin: dark
  nav_pages:
    - about.md
    - posts.md

  social_links:
    - title: "Minima Theme repository at GitHub"
      icon: github
      url: "https://github.com/jekyll/minima"
    - title: "Jekyll at X (formerly Twitter)"
      icon: x-twitter
      url: "https://x.com/jekyllrb"

# Uncomment if needed
# sass:
#   quiet_deps: true
#   silence_deprecations: [import]
e
