public class POJO {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private String email;
    private String school;
    private String studentID;
    private String githubUsername;
    private LocalDateTime createdAt;
    private String accountType;

    // Generated by @NoArgsConstructor
    public POJO() {
    }

    // Generated by @AllArgsConstructor
    public POJO(Long id, String name, String email, String school, String studentID, String githubUsername, LocalDateTime createdAt, String accountType) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.school = school;
        this.studentID = studentID;
        this.githubUsername = githubUsername;
        this.createdAt = createdAt;
        this.accountType = accountType;
    }

    // Generated by @Data (Getters)
    public Long getId() { return this.id; }
    public String getName() { return this.name; }
    public String getEmail() { return this.email; }
    public String getSchool() { return this.school; }
    public String getStudentID() { return this.studentID; }
    public String getGithubUsername() { return this.githubUsername; }
    public LocalDateTime getCreatedAt() { return this.createdAt; }
    public String getAccountType() { return this.accountType; }

    // Generated by @Data (Setters)
    public void setId(Long id) { this.id = id; }
    public void setName(String name) { this.name = name; }
    public void setEmail(String email) { this.email = email; }
    public void setSchool(String school) { this.school = school; }
    public void setStudentID(String studentID) { this.studentID = studentID; }
    public void setGithubUsername(String githubUsername) { this.githubUsername = githubUsername; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public void setAccountType(String accountType) { this.accountType = accountType; }

    // Generated by @Data (Utility Methods)
    public boolean equals(Object o) { ... }
    protected boolean canEqual(Object other) { ... }
    public int hashCode() { ... }
    public String toString() { ... }
}